---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-forge-charmander
  namespace: minecraft-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    nameOverride: dev
    image: itzg/minecraft-server
    imageTag: java8-openj9
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 20Gi
    resources:
      requests:
        memory: 9Gi
      limits:
        memory: 12Gi
    extraEnv:
      USE_AIKAR_FLAGS: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.12.2"
      jvmOpts: "-Xmns1G -Xmnx3G -Xgcpolicy:balanced -Xdisableexplicitgc -Dfml.readTimeout=300"
      forgeVersion: "14.23.5.2854"
      gameMode: "0"
      forcegameMode: false
      type: FORGE
      pvp: false
      forceReDownload: true
      difficulty: "0"
      levelType: DEFAULT
      playerIdleTimeout: 300
      maxWorldSize: 29999984
      maxPlayers: 120
      viewDistance: 4
      maxTickTime: -1
      memory: 6G
      motd: "forge-charmander"
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
