---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.13.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #  repository: grafana/grafana
    #  tag: 6.7.6
    deploymentStrategy:
      type: Recreate
    podAnnotations:
      backup.velero.io/backup-volumes: storage
      configmap.reloader.stakater.com/reload: "grafana"
    persistence:
      enabled: true
      storageClassName: "longhorn"
      size: 10Gi
      accessModes:
        - ReadWriteOnce
    env:
      GF_EXPLORE_ENABLED: true
      GF_DISABLE_SANITIZE_HTML: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts: [grafana.pixelmontogo.com]
      tls:
        - hosts:
            - grafana.pixelmontogo.com
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - grafana-clock-panel
      - vonage-status-panel
      - grafana-worldmap-panel
    serviceMonitor:
      enabled: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        1-node-exporter:
          url: https://grafana.com/api/dashboards/11074/revisions/9/download
          datasource: Prometheus
        cpu-utilization:
          url: https://grafana.com/api/dashboards/10842/revisions/1/download
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/v0.7.6/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/v0.7.6/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
        metallb:
          url: https://grafana.com/api/dashboards/14127/revisions/1/download
          datasource: Prometheus
        minecraft:
          url: https://raw.githubusercontent.com/pixelmontogo/k8s-gitops/master/monitoring/grafana/dashboards/minecraft-server.json
          datasource: Prometheus
        minio-overview:
          url: https://raw.githubusercontent.com/pixelmontogo/k8s-gitops/master/monitoring/grafana/dashboards/minio_overview.json
          datasource: Prometheus
        nginx-dashboard:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
          datasource: Prometheus
        node-exporter-full:
          url: https://raw.githubusercontent.com/pixelmontogo/k8s-gitops/master/monitoring/grafana/dashboards/node_exporter_full.json
          datasource: Prometheus
        promcord:
          url: https://raw.githubusercontent.com/nimarion/promcord/master/grafana.json
          datasource: Prometheus
        prometheus-exporter-summary:
          url: https://raw.githubusercontent.com/pixelmontogo/k8s-gitops/master/monitoring/grafana/dashboards/prometheus_exporter_summary.json
          datasource: Prometheus
        uptimerobot:
          url: https://raw.githubusercontent.com/lekpamartin/uptimerobot_exporter/master/dashboards/grafana.json
          datasource: Prometheus
        velero:
          url: https://grafana.com/api/dashboards/11055/revisions/2/download
          datasource: Prometheus
    sidecar:
      datasources:
        enabled: true
        searchNamespace: ALL
        # defaultDatasourceEnabled: false
      dashboards:
        enabled: true
        searchNamespace: ALL
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://thanos-query-http:10902/
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
    grafana.ini:
      server:
        root_url: "https://grafana.pixelmontogo.com"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
  valuesFrom:
    - kind: Secret
      name: "grafana-helm-values"
