---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-forge-charmander
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: 1.8.0-adopt13
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        size: 100Gi
    resources:
      requests:
        memory: 16Gi
      limits:
        memory: 20Gi
    extraEnv:
      USE_AIKAR_FLAGS: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.12.2"
      gameMode: "0"
      forcegameMode: false
      type: FORGE
      pvp: false
      forceReDownload: true
      difficulty: "0"
      levelType: DEFAULT
      playerIdleTimeout: 300
      maxWorldSize: 29999984
      maxPlayers: 120
      viewDistance: 4
      maxTickTime: -1
      memory: 16G
      motd: "forge-charmander"
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
