---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-proxy
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/bungeecord
    imageTag: 1.5.0-adopt13
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    minecraftProxy:
      type: WATERFALL
      serviceType: LoadBalancer
      loadBalancerIP: 138.201.203.183
      externalTrafficPolicy: Local
      memory: 2G
      rcon:
        enabled: true
        serviceType: ClusterIP
