{
 "title": "PTG Minecraft",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(mc_tps, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n  -\n  kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n)\n/\nkubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n* 100\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Lowest TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"}"
    }
   ]
  },
  {
   "title": "Players per world",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mc_players_online_total{container=~\"$container\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Network usage per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps", "label": "transmit (-) / receive (+)" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))\n",
     "legendFormat": "{{workload}}_receive"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))\n",
     "legendFormat": "{{workload}}_transmit"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{workload}}_receive_count"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{workload}}_transmit_count"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_players_online_total{container=~\"$container\"}) by (world)",
     "legendFormat": "Online ({{world}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\", workload=~\"$container\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "scalar(kube_resourcequota{type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{container=~\"$container\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', container=~\"$container\"}",
     "legendFormat": "Allocated - {{container}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', container=~\"$container\"} - scalar(mc_jvm_memory{type='free', container=~\"$container\"})",
     "legendFormat": "Used - {{container}}"
    }
   ]
  },
  {
   "title": "Tick Durations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds per tick" }
   ],
   "targets": [
    {
     "expr": "mc_tick_duration_max{container=~\"$container\"}/1e6",
     "legendFormat": "Max - {{container}}"
    },
    {
     "expr": "mc_tick_duration_average{container=~\"$container\"}/1e6",
     "legendFormat": "Avg - {{container}}"
    }
   ]
  },
  {
   "title": "Entity Counts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"}) by (world, level, type)",
     "legendFormat": "{{world}}:  {{type}}"
    }
   ]
  }
 ]
}