---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultDataPath: /longhorn
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      #backupTarget: nfs://10.10.10.31:/mnt/tardisk/k3s
    ingress:
      enabled: true
      host: longhorn.pixelmontogo.com
      tlsSecret: longhorn-cert
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://auth.pixelmontogo.com/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.pixelmontogo.com/oauth2/start
