---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-helm-values
  namespace: monitoring
spec:
  keys:
    - values.yaml
  path: secrets/monitoring/minio/minio-helm-values
  type: Opaque
